# Generated by Django 3.1.3 on 2020-11-05 17:05

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('follows', models.ManyToManyField(blank=True, related_name='_useracc_follows_+', to='api.UserAcc')),
                ('friends', models.ManyToManyField(blank=True, to='api.UserAcc')),
                ('home_country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.country')),
                ('interests', models.ManyToManyField(blank=True, to='api.Interest')),
                ('was_here', models.ManyToManyField(blank=True, related_name='_useracc_was_here_+', to='api.Country')),
                ('will_go', models.ManyToManyField(blank=True, related_name='_useracc_will_go_+', to='api.Country')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='_post_likes_+', to='api.UserAcc')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useracc')),
            ],
        ),
        migrations.CreateModel(
            name='NextTravel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting', models.DateField()),
                ('until', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.useracc')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.country')),
            ],
        ),
    ]
