# Generated by Django 3.1.3 on 2020-11-05 16:42

from django.db import migrations
from ..migration_adders import add_countries


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_countries)
    ]
