name: Testing
on: push

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Run Django unit tests
        run: |
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
          pip3 install wheel
          pip3 install pipenv
          cd backend
          pipenv run pip freeze > requirements.txt
          pip3 install requirements.txt
          python3 manage.py test
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run React unit tests
        run: |
          cd frontend
          npm install
          npm test
