name: Testing
on: push

jobs:
  test_backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Python 3.8
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8.1'
      - uses: dschep/install-pipenv-action@v1
      - name: Run Django unit tests
        run: |
          cd backend
          pipenv install
          pipenv run ./manage.py test
  test_frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run React unit tests
        run: |
          cd frontend
          npm install
          npm test
